### ISSUE TITLE
ArrowFormat does not work with pyarrow 15.0.0

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#480]
If you try to do something like this:

```python
from yt.wrapper import YtClient
from yt.wrapper.default_config import get_config_from_env
from yt.wrapper.format import ArrowFormat
import pyarrow


def main():
    client = YtClient(get_config_from_env())

    table_stream = client.read_table("//tmp/table", ArrowFormat(raw=True))

    total_size = 0
    with pyarrow.ipc.open_stream(table_stream) as reader:
        print(reader.schema)
        for batch in reader:
            total_size += len(batch)

    print(total_size)

main()
```

You will gеt
```shell
Traceback (most recent call last):
  File "/home/echunaev/.local/lib/python3.11/site-packages/pyarrow/ipc.py", line 52, in __init__
    self._open(source, options=options, memory_pool=memory_pool)
AttributeError: 'ResponseStreamWithReadRow' object has no attribute 'closed'
Traceback (most recent call last):
    with pyarrow.ipc.open_stream(table_stream) as reader:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# <some lines>
  File "/home/echunaev/.local/lib/python3.11/site-packages/pyarrow/ipc.py", line 190, in open_stream
    return RecordBatchStreamReader(source, options=options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/echunaev/.local/lib/python3.11/site-packages/pyarrow/ipc.py", line 52, in __init__
    self._open(source, options=options, memory_pool=memory_pool)
  File "pyarrow/ipc.pxi", line 972, in pyarrow.lib._RecordBatchStreamReader._open
  File "pyarrow/ipc.pxi", line 596, in pyarrow.lib._get_input_stream
  File "pyarrow/io.pxi", line 2059, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 215, in pyarrow.lib.NativeFile.get_input_stream
  File "pyarrow/io.pxi", line 227, in pyarrow.lib.NativeFile._assert_readable
  File "pyarrow/io.pxi", line 224, in pyarrow.lib.NativeFile._assert_open
ValueError: I/O operation on closed file

```

**Comment by denvr** [comment]
Make `ResponseStream` looks more file-like - it seems like a is good idea

**Comment by chegoryu** [comment]
Are you sure that this is ok for `EmptyResponseStream`?

https://github.com/ytsaurus/ytsaurus/blob/4761dbf01008cb5dc9a34f4cc81e2794412ce7aa/yt/python/yt/wrapper/response_stream.py#L156-L158

You will get confusing error because stream is closed before first read from it.
