### PR TITLE
Cleanup disk quota options

### PR DESCRIPTION
**Pull request by koct9i**
Add slot location option for enabling disk quota for sandbox directories.
It is implemented as user disk quota or as porto (project) quota volume.
    
Root volume quota works independently but enforces the same limits.
It is implemented only for porto volume.

### CODE REVIEW

File: yt/yt/server/lib/exec_node/config.cpp [hunk 1]
```diff
@@ -146,6 +146,9 @@ void TSlotManagerConfig::Register(TRegistrar registrar)
 {
     registrar.Parameter("locations", &TThis::Locations);
 
+    registrar.Parameter("enable_disk_quota", &TThis::EnableDiskQuota)
```
Comment (gritukan) [inline yt/yt/server/lib/exec_node/config.cpp:149]: Maybe quotas?

Comment (koct9i) [reply yt/yt/server/lib/exec_node/config.cpp:149]: In volume-manager config it's called "enable_disk_quota"

**Review by Kontakter — APPROVED** [review]

**Review by Kontakter — CHANGES_REQUESTED** [review]
There are compilation errors:
```
$(SOURCE_ROOT)/yt/yt/server/node/exec_node/job.cpp:2729:38: error: use of undeclared identifier 'Config_'
    options.EnableSandboxDiskQuota = Config_->SlotManager->EnableDiskQuota;
...
$(SOURCE_ROOT)/yt/yt/server/node/data_node/unittests/volume_manager_ut.cpp:352:10: error: field designator 'HasRootFSQuota' does not refer to any field in type 'TUserSandboxOptions'
        .HasRootFSQuota = true,
         ^
$(SOURCE_ROOT)/yt/yt/server/node/data_node/unittests/volume_manager_ut.cpp:353:10: error: field designator 'EnableDiskQuota' does not refer to any field in type 'TUserSandboxOptions'
        .EnableDiskQuota = false
```

File: yt/yt/server/lib/exec_node/config.cpp (hunk 1 above)
Comment (koct9i) [reply yt/yt/server/lib/exec_node/config.cpp]: I've redesigned it into per slot-location option.

File: yt/yt/server/node/exec_node/volume_manager.cpp [hunk 2]
```diff
@@ -1302,7 +1302,8 @@ class TLayerLocation
             {"place", PlacePath_}
         };
 
-        if (options.EnableDiskQuota && options.HasRootFSQuota) {
+        // NB: Root volume quota is independent from sandbox quota but enforces the same limits.
+        if (options.EnableRootVolumeDiskQuota) {
```
Comment (koct9i) [inline yt/yt/server/node/exec_node/volume_manager.cpp:1306]: As I see this branch is dead. I leave fixing this to actual porto users. =)

File: yt/yt/server/node/exec_node/volume_manager.cpp [hunk 3]
```diff
@@ -1302,7 +1302,8 @@ class TLayerLocation
...
             volumeProperties["user"] = ToString(options.UserId);
```
Comment (koct9i) [inline yt/yt/server/node/exec_node/volume_manager.cpp:1307]: BTW in porto volume limit is implemented as project-quota which have nothing to do with "user".

File: yt/yt/server/lib/exec_node/config.cpp [hunk 4]
```diff
@@ -109,15 +109,19 @@ void TCriJobEnvironmentConfig::Register(TRegistrar registrar)
 
 void TSlotLocationConfig::Register(TRegistrar registrar)
 {
-    registrar.Parameter("disk_quota", &TThis::DiskQuota)
+    registrar.Parameter("disk_quota", &TThis::MaxDiskSpace)
```
Comment (Kontakter) [inline yt/yt/server/lib/exec_node/config.cpp:112]: Let name it `max_disk_space` in this case and add an alias for `disk_quota`

**Review by Kontakter — APPROVED** [review]

**Review by Kontakter — CHANGES_REQUESTED** [review]
There are still some build errors:
```
yt/yt/server/node/data_node/unittests/volume_manager_ut.cpp:352:10: error: field designator 'HasRootFSQuota' does not refer to any field in type 'TUserSandboxOptions'
        .HasRootFSQuota = true,
         ^
yt/yt/server/node/data_node/unittests/volume_manager_ut.cpp:353:10: error: field designator 'EnableDiskQuota' does not refer to any field in type 'TUserSandboxOptions'
        .EnableDiskQuota = false
         ^
2 errors generated.
```

File: yt/yt/server/lib/exec_node/config.cpp (hunk 4 above)
Comment (koct9i) [reply yt/yt/server/lib/exec_node/config.cpp:112]: I'll drop this renaming.

**Comment by koct9i** [comment]
> volume_manager_ut.cpp

This file not in OS
https://github.com/ytsaurus/ytsaurus/commit/579a2c2b96545e42aa2db420225914a0e33b8e81

**Review by Kontakter — APPROVED** [review]
